### PR TITLE
Fix #10

### LINKED ISSUE #10: I got KeyError: TextField when I tried using EncryptedIntegerField
Hi,

I was developing a reusable-applications to use in my projects.
I decided to encrypt some IntegerFields by using EncryptedIntegerField from  django-fernet-encrypted-fields 

So then when I tried to test my app by tox I got this error:

> ".tox/py310-4.0/lib/python3.10/site-packages/django/db/backends/base/operations.py", line 673, in integer_field_range  return self.integer_field_ranges[internal_type]

> KeyError: 'TextField'

As you can see in the error message I'm using python 3.10 and django 4.0.4

I searched for this error and I found a similar problem in [django-cryptography](https://github.com/georgemarshall/django-cryptography) project in the issue [#16](https://github.com/georgemarshall/django-cryptography/issues/16)

The suggested solution there was using a DecimalField with decimal_place=0   instead of an IntegerField

I hope there is a possible solution to use IntegerField as I'm trying to keep integer data in my model.

### PR DESCRIPTION
**Pull request by frgmt**

### CODE REVIEW

**Comment by frgmt** [comment]
@StevenMapes @hendrikschneider What do you think about this approach? I have removed the validation for integer since this package is treating everything as a textfield. Also, I was getting errors during makemigrations and I don't know how to write this testcase...

**Comment by StevenMapes** [comment]
I'll have to have a more detailed look but if removing the validations means someone would pass a string into the field and have it be encrypted without raising a validation error then I'd say it needs another fix as you'd still want the input validation to run prior to encryption otherwise there's no point in having the different types of encrypted fields you may as well just have one.

I'm very busy today but will try to pull down and test Ali's example app along with your solution.

I've not had a need to run a testcase over migrations before myself let alone makemigrations but this could be a useful package for both https://github.com/wemake-services/django-test-migrations

**Comment by hendrikschneider** [comment]
I also think the validation should be kept. When checking the validation function I saw the validators are checking for the min and max value of the input. As this lib does not make a difference between the difference IntegerField types (SmallInt, Integer, BigInteger, ...) it would be enough to check only if the input is an int (not checking the boundaries).

Idea:
```
def is_integer(value):
    if type(value) != int:
        raise ValidationError(
            _('%(value)s is not an integer number'),
            params={'value': value},
        )

class EncryptedIntegerField(EncryptedFieldMixin, models.IntegerField):
  @cached_property
          def validators(self):
              return [*self.default_validators, *self._validators, is_integer]
```

**Comment by Ali-Javanmardi** [comment]
@hendrikschneider , @StevenMapes , @frgmt 
Thank you all to investigating this problem so fast. Actually for an encryption solution I came to this project as I found it so clean and minimalist .

> `As this lib does not make a difference between the difference IntegerField types (SmallInt, Integer, BigInteger, ...) it could be enough to check only if the input is an int (not checking the boundaries).`

But in reply to above paragraph, I should say maximum value is so important for me. In django models I have chosen positive small integer  to keep my number 16bits long. If we don't have a fixed maximum length at least I will be in trouble.
To make it clear, I want to use this number as a security value and so I want to do bit-wise operation on that.
If the number is longer than what I expect, a ~ (bitwise not) will return me an unknown value.
Although this is my personal case I think keeping that min max validation rule as an important feature is valuable.

Thanks,

**Comment by frgmt** [comment]
I tried different approach. 
But, I realized that every fields can go through text.. 🤣

**Comment by frgmt** [comment]
@Ali-Javanmardi I fixed min and max value validation. Please check it.
https://github.com/frgmt/django-fernet-encrypted-fields/pull/11/commits/8c6563c0f3ce70ea1fbeb354f5f4b90fc732c034#diff-d814f2c8886a6f57dff41b7b53409ec35a8d72ef4b18ad735a0a2c2730abade9R92-R98

**Comment by Ali-Javanmardi** [comment]
@frgmt 

I installed branch hotfix/EncryptedIntegerField in my virtualenv

> ~/dev/try_encrypted_fields > pip freeze | egrep fernet                                                                                                                                 
> django-fernet-encrypted-fields==0.1.2
> `

but by running my test project in this venv still I get same error:

> ~/dev/try_encrypted_fields > tox

```
GLOB sdist-make: ~/dev/try_encrypted_fields/setup.py
py310-dj40 inst-nodeps: ~/dev/try_encrypted_fields/.tox/.tmp/package/1/enc_field-0.0.1.zip
py310-dj40 installed: ~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/pip/_internal/locations/_distutils.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives,  from distutils.cmd import Command as DistutilsCommand,/usr/lib/python3.10/distutils/command/install.py:13: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead,  from distutils.sysconfig import get_config_vars,asgiref==3.5.1,cffi==1.15.0,cryptography==37.0.2,Django==4.0.4,django-fernet-encrypted-fields==0.1.1,enc-field==0.0.1,pycparser==2.21,sqlparse==0.4.2
py310-dj40 run-test-pre: PYTHONHASHSEED='988131120'
py310-dj40 run-test: commands[0] | django-admin --version
4.0.4
py310-dj40 run-test: commands[1] | ~/dev/try_encrypted_fields/.tox/py310-dj40/bin/python make_migrations.py
~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/conf/__init__.py:206: RemovedInDjango50Warning: The default value of USE_TZ will change from False to True in Django 5.0. Set USE_TZ to False in your project settings if you want to keep the current default behavior.
  warnings.warn(
Traceback (most recent call last):
  File "~/dev/try_encrypted_fields/make_migrations.py", line 9, in <module>
    execute_from_command_line(args)
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/core/management/base.py", line 455, in execute
    self.check()
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/core/checks/model_checks.py", line 36, in check_all_models
    errors.extend(model.check(**kwargs))
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/db/models/base.py", line 1442, in check
    *cls._check_fields(**kwargs),
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/db/models/base.py", line 1554, in _check_fields
    errors.extend(field.check(**kwargs))
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1931, in check
    *super().check(**kwargs),
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 252, in check
    *self._check_validators(),
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 413, in _check_validators
    for i, validator in enumerate(self.validators):
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1954, in validators
    min_value, max_value = connection.ops.integer_field_range(internal_type)
  File "~/dev/try_encrypted_fields/.tox/py310-dj40/lib/python3.10/site-packages/django/db/backends/base/operations.py", line 673, in integer_field_range
    return self.integer_field_ranges[internal_type]
KeyError: 'TextField'
ERROR: InvocationError for command ~/dev/try_encrypted_fields/.tox/py310-dj40/bin/python make_migrations.py (exited with code 1)
______________________________________________________________________________________________________________________ summary ______________________________________________________________________________________________________________________
ERROR:   py310-dj40: commands failed



```

and here is make_migrations.py:


```
#!/usr/bin/env python
 import os
 import sys
 
 if __name__ == "__main__":
     os.environ.setdefault("DJANGO_SETTINGS_MODULE", "migrations_settings")
     from django.core.management import execute_from_command_line
     args = sys.argv + ["makemigrations", "enc_field"]
     execute_from_command_line(args)
```


and this is migrations_settings.py:

```
SECRET_KEY = 'fake-key'

INSTALLED_APPS = [
    "encrypted_fields",
    'enc_field.apps.EncFieldConfig'
]

```

and this is models.py:
```
from django.db import models

from encrypted_fields.fields import EncryptedIntegerField, EncryptedCharField

class EncFields(models.Model):
  enc_int = EncryptedIntegerField(default=0, blank=True)
  # enc_char = EncryptedCharField(max_length=10, default='test', blank=True)


```

**Comment by Ali-Javanmardi** [comment]
@frgmt 

I installed branch hotfix/EncryptedIntegerField
```
pip freeze | egrep fernet
django-fernet-encrypted-fields==0.1.2
```

and then :
`python ./make_migrations.py `

```
Migrations for 'enc_field':
  enc_field/migrations/0001_initial.py
    - Create model EncFields
```

and finally runtests:
`python ./runtests.py`

```
Found 1 test(s).
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: encrypted_fields
  Apply all migrations: enc_field
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying enc_field.0001_initial... OK
System check identified no issues (0 silenced).
test_integer_field_encrypted (enc_field.tests.Test_EncFields) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.068s

OK
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
```

So, it seems your changes are working.

But in my model I just used: default=0

I will add min and max limits in few minutes and try again above steps

**Comment by Ali-Javanmardi** [comment]
@frgmt 
I changed models.py:
```

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from encrypted_fields.fields import EncryptedIntegerField, EncryptedCharField

class EncFields(models.Model):
  enc_int = EncryptedIntegerField(default=0, blank=True, validators=[MinValueValidator(1), MaxValueValidator(100)])
```

and make migrations again:

`python ./make_migrations.py`
```
Migrations for 'enc_field':
  enc_field/migrations/0002_alter_encfields_enc_int.py
    - Alter field enc_int on encfields

```

and ran test again:
`python ./runtests.py`
```

Found 1 test(s).
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: encrypted_fields
  Apply all migrations: enc_field
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying enc_field.0001_initial... OK
  Applying enc_field.0002_alter_encfields_enc_int... OK
System check identified no issues (0 silenced).
test_integer_field_encrypted (enc_field.tests.Test_EncFields) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.070s

OK
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...

```


So setting min and max validators also works well

Thanks for all your efforts.

**Comment by Ali-Javanmardi** [comment]
It seems MaxValueValidator does not through error with this changes:

As you can see in above comment I changed model.py to: 
```
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from encrypted_fields.fields import EncryptedIntegerField, EncryptedCharField

class EncFields(models.Model):
  enc_int = EncryptedIntegerField(default=0, blank=True, validators=[MinValueValidator(1), MaxValueValidator(100)])

```

so there is a max limit of 100 in the field.

but when I tried this test:

```
    def test_integer_field_max_limit_encrypted(self):
        plaintext = 142

        model = EncFields()
        model.enc_int = plaintext
        model.save()

        ciphertext = self.get_db_value("enc_int", model.id)

        self.assertNotEqual(plaintext, ciphertext)
        self.assertNotEqual(plaintext, str(ciphertext))

        fresh_model = EncFields.objects.get(id=model.id)
        self.assertEqual(fresh_model.enc_int, plaintext)
```

I got an OK result from my test:
```
Found 2 test(s).
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: encrypted_fields
  Apply all migrations: enc_field
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying enc_field.0001_initial... OK
  Applying enc_field.0002_alter_encfields_enc_int... OK
System check identified no issues (0 silenced).
test_integer_field_encrypted (enc_field.tests.Test_EncFields) ... ok
test_integer_field_max_limit_encrypted (enc_field.tests.Test_EncFields) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.070s

OK
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
```

I expected to receive a validation error by that test as there was a limit of (100) in the model field and I assigned (142) in the test.

**Comment by frgmt** [comment]
@Ali-Javanmardi You need to call full_clean before save.
https://stackoverflow.com/questions/849142/how-to-limit-the-maximum-value-of-a-numeric-field-in-a-django-model

**Comment by Ali-Javanmardi** [comment]
@frgmt  You are right,
I forgot to do that.

Now test result after full_clean shows expected error:
```
Found 2 test(s).
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: encrypted_fields
  Apply all migrations: enc_field
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying enc_field.0001_initial... OK
  Applying enc_field.0002_alter_encfields_enc_int... OK
System check identified no issues (0 silenced).
test_integer_field_encrypted (enc_field.tests.Test_EncFields) ... ok
test_integer_field_max_limit_encrypted (enc_field.tests.Test_EncFields) ... ERROR

======================================================================
ERROR: test_integer_field_max_limit_encrypted (enc_field.tests.Test_EncFields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/al/dev/try_encrypted_fields/enc_field/tests.py", line 47, in test_integer_field_max_limit_encrypted
    model.full_clean()
  File "/home/al/dev/try_encrypted_fields/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1405, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'enc_int': ['Ensure this value is less than or equal to 100.']}

----------------------------------------------------------------------
Ran 2 tests in 0.070s

FAILED (errors=1)
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...

```

**Comment by frgmt** [comment]
I merged into main. Let me know if there are any problems.

**Pull request merged**
